### ISSUE TITLE
دیتابیس کجاست؟

### ISSUE THREAD

**Issue by Masihgh** [ganjoor/desktop#12]
واقعا عالی کیف کردم

**Comment by hrmoh** [comment]
درود
اطلاعات گنجور در قالب پروژه بازمتن و رایگان گنجور رومیزی و در قالب SQLite برای عموم در دسترس است.
شما می‌توانید یک نسخه از فایل دیتابیس را از این نشانی دریافت کنید:
https://github.com/ganjoor/desktop/releases/tag/v2.81
یا برنامه را نصب کنید:
http://dg.ganjoor.net/
و پس از «دریافت مجموعه‌ها» جهت دسترسی به آخرین اطلاعات از طریق پیکربندی فایل دیتابیس را پیدا و استفاده کنید (ganjoor.s3db).
از طریق منوی ابزارها نیز می‌توانید ویرایشگر برنامه را باز کنید و در ویرایشگر از طریق منوی بازشوی دکمهٔ ابزارها اطلاعات را به فایل متنی ارسال کنید.
تندرست باشید.

**Comment by xmha97** [comment]
> دیتابیس کجاست؟

اینجاست.
```
%LocalAppData%\ganjoor\ganjoor.s3db
```
