### ISSUE TITLE
درخواست: اپلیکیشن مک

### ISSUE THREAD

**Issue by mderis** [ganjoor/desktop#44]
درود فراوان بر دوستان
با توجه به این امر که تعداد قابل توجهی از علاقه‌مندان به شعر و خوانش، وظیفه‌ی خود می‌دانند که با ایجاد فایل های صوتی برای شعر های دشوار و کمتر توجه شده، خدمتی به جامعه‌ی ادب پارسی نمایند و در این بین هستند افرادی که کامپیوتر های مبتنی بر ویندوز در اختیار ندارند، درخواست بنده این است که در صورت امکان، تهیه‌ی نرم‌افزاری تحت مک برای این امر در دستور کار قرار گیرد.

با تشکر فراوان.

**Comment by hrmoh** [comment]
با سلام
این که این اپلیکیشن روی مک در دسترس قرار بگیرد یک درخواست ساده نیست و قطعاً اگر به آسانی شدنی بود تا به حال انجام شده بود.
در این زمینه فورک برنامه‌های چندسکویی مثل ساغر:
http://pozh.org/saaghar/
و غزل:
https://ghazal.rosybit.com/
توسط دوستان علاقمند و پیاده‌سازی این قابلیت ممکن است زودتر به نتیجه برسد.
